# Change to you title
title = "Karzok"

#base_url = "http://localhost:8080"
base_url = "https://fmatch.org/karzok"

default_language = "en"

build_search_index = true

#minify_html = true

#hard_link_static = true

compile_sass = true

taxonomies = [
    {name = "authors"},
]

[slugify]
paths = "on"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

render_emoji = true

[extra]
# logotype
favicon = "assets/favicon.ico"

# github
version = "https://api.github.com/repos/kogeletey/karzok/releases/latest"
cdnurl = "https://get.re128.net/"

# special parameter for develop
#assets_url = "https://get.re128.net/_/karzok"
#devmode = true

#localcdn = true

show_word_count = true
show_reading_time = true
relative_path = true

[[extra.header_left]]
text = "Meta"
link = "$base_url/meta"

# experiments in container header, disabled
#[[extra.meta.container]]
#title = "Meta"
#description = "meta"
#url  = "/home"

[[extra.header_right]]
link = "https://github.com/kogeletey/karzok"
svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33c.85 0 1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2z" fill="currentColor"></path></svg>'

[[extra.header_right]]
link = "https://sr.ht/~kogeletey/karzok"
svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M11.5 3a9.5 9.5 0 1 1 0 19a9.5 9.5 0 0 1 0-19zm0 1a8.5 8.5 0 1 0 0 17a8.5 8.5 0 0 0 0-17z" fill="currentColor"></path></svg>'

[[extra.menu]]
text = "Install"
link = "$base_url/install"

[[extra.menu]]
text = "Configure"
link = "$base_url/configure"

[[extra.menu]]
text = "Contribute"
link = "$base_url/contribute"

